### ISSUE TITLE
scdl.getSetInfo(url) returns all tracks in a playlist but only the first few tracks has info.

### ISSUE THREAD

**Issue by th13n-h4ck3r** [zackradisic/node-soundcloud-downloader#16]
Thank you for making this repo, and streaming soundcloud music possible. I've encounter the following problem when using it.

[Here](https://imgur.com/a/vwHZhmc) is a picture of the console.log() prints out after calling `await scdl.getSetInfo(url)`. This happens on any playlist url, https://soundcloud.com/user-845046062/sets/playlist for example.

When I go to the playlist link and copy the track url that doesn't have the info printed and use `scdl.getInfo(url), it shows all the track info normally.

Any clues? Could it be that I'm not providing a ClienID?
Thank you so much!

**Comment by zackradisic** [comment]
Tried this out for myself and it appears that Soundcloud only provides information for the first 5 tracks of a playlist. I feel like there is probably some query parameter I can put in the api request to get the full JSON response, but Soundcloud's api v2 is so esoteric and undocumented that I don't know what that query parameter might be or if it's even possible.

What I can do for now is change `scdl.getSetInfo(url)` so that it individually retrieves the track info for the remaining tracks.

**Comment by th13n-h4ck3r** [comment]
Yeah, that would be a work-around until we have a solution to the current problem.

Thank you for your response!

**Comment by zackradisic** [comment]
@th13n-h4ck3r I've added an additional parameter to the function: [`scdl.getSetInfo(url: string, full = false, clientID?: string`](https://zackradisic.github.io/node-soundcloud-downloader/classes/_index_.scdl.html#getsetinfo). If full = true then the function will retrieve track info for all tracks.

I've tested this with the playlist you provided in your first comment, and it took ~10 seconds to execute because it has to make individual API requests for each of the remaining 25 tracks in the playlist. There's probably a way to optimize this, but I'm leaving it as is for now.

Depending on the circumstances of your use case, it may be more efficient to fetch individual track data when needed, rather than loading them all at once. I've added an additional function [`scdl.getTrackInfoByID(id: number, clientID?: string)`](https://zackradisic.github.io/node-soundcloud-downloader/classes/_index_.scdl.html#gettrackinfobyid) which allows you to do just that.

Thanks for bringing this problem to my attention.

**Comment by th13n-h4ck3r** [comment]
@zackradisic can you utilize `Promise.all()` in the `scdl.getSetInfo()` so that it can request api in parallel instead of individually?
Maybe something like: 
`let playlist = await Promise.all(tracks.map(id =>{ 
     return await scdl.getTrackInfoByID(id);
}));`
I don't know if this would work on typescript as I only know javascript, but it's an idea that might be useful.

**Comment by zackradisic** [comment]
@th13n-h4ck3r Good thinking, I completely forgot about `Promise.all()`. However, I found an an API endpoint that retrieves track info for multiple tracks at a time which should be faster than making individual requests. The current version of the package is using this method to get playlist info.
