### ISSUE TITLE
Bug: search() - Request to next_href link fails with 404 error

### ISSUE THREAD

**Issue by clarnx** [zackradisic/node-soundcloud-downloader#49]
When you use the search method, the response is a paginated query with the field "next_href". The collection of tracks field is an array that is limited to 10 values.
So trying to visit "next_href" link to get the remaining collection of tracks results in an error.

**Comment by zackradisic** [comment]
Thanks for bringing this to my attention, I'll investigate the problem as soon as I get the chance.

**Comment by clarnx** [comment]
Okay l will be waiting for your feedback

**Comment by zackradisic** [comment]
@clarnx, can you show me the error log? I believe the issue may be that the `next_href` link requires you to provide the client ID as a query parameter. You cannot just simply make a GET request to that link. 

That being said, it should be the responsibility of the module itself to handle this functionality. In the next version, I'm thinking of adding the option to call the search method with the `next_href` link which will handle this for you. Also, I plan to support configuring the limit of the returned array too.

For now, a temporary solution to this problem is to append your client id as a query parameter to the URL. ex/
```typescript

const paginatedQuery = await scdl.search('tracks', 'aksdhfkjahdf')
const url = paginatedQuery.next_href + '&client_id=' + await scdl.getClientID()
```

**Comment by clarnx** [comment]
@zackradisic yes I figured a couple of hours ago that I had to append the Client ID and it worked though I was wondering why this was not done automatically.

Anyway thanks for the feedback

**Comment by zackradisic** [comment]
@clarnx, this is now fixed with the latest release. Check it out [here](https://github.com/zackradisic/node-soundcloud-downloader/releases/tag/v0.2.4). Thanks again for bringing this to my attention.
